### ISSUE TITLE
TDM-MinGW compile error

### ISSUE THREAD

**Issue by gvanem** [shixiongfei/nio4c#1]
Building using MSVC or clang-cl is no problem. But TDM-gcc (i.e. MinGW) complains on `nio4c_socket.c`:
```
nio4c_socket.c:38:30: error: static declaration of 'in6addr_any' follows non-static declaration
 static const struct in6_addr in6addr_any = { {{0}} };
                              ^
In file included from nio4c.h:40:0,
                 from nio4c_socket.c:12:
f:/MinGW32/TDM-gcc/x86_64-w64-mingw32/include/WS2tcpip.h:83:32: note: previous declaration of 'in6addr_any' was here
   extern const struct in6_addr in6addr_any;
                                ^
```
But dropping the `static` keeps `gcc` (ver 5.1) happy:
```diff
--- a/nio4c_socket.c 2020-03-22 10:13:18
+++ b/nio4c_socket.c 2020-03-22 10:10:39
@@ -35,7 +35,7 @@
 #include <mstcpip.h>
 #include <process.h>

-static const struct in6_addr in6addr_any = { {{0}} };
+const struct in6_addr in6addr_any = { {{0}} };

 #define socklen_t int
 #define socket_errno() WSAGetLastError()
```

**Comment by shixiongfei** [comment]
It looks like the `in6addr_any ` is already defined by MinGW and I have fixed the problem, please update code.

**Comment by gvanem** [comment]
Well, it works if you drop it for MSVC too. Those symbols seems to be just read-only constants added to `ws2_32.lib`. But I guess it depends on the `ws2_32.lib` version.

Check with `nm ws2_32.lib | grep ' R _in6addr_'`.

**Comment by shixiongfei** [comment]
Yes, the new version of the Windows SDK adds a lot of compatibilities, but I think the old version may still need this code

**Comment by shixiongfei** [comment]
Fixed in https://github.com/shixiongfei/nio4c/commit/55f0e2821b43b4a72915b8ff35e65a264ca3c7a3
